### ISSUE TITLE
TODO for Smart Mirror

### ISSUE THREAD

**Issue by VorpalBlade** [VorpalBlade/freecad_macros#1]
Personal todo list. ***Please do NOT suggest features here, but use either a new bug or [the FreeCAD forum thread](https://forum.freecadweb.org/viewtopic.php?style=4&f=22&t=53584)***

## Limitations
- [ ] Set construction flag for copied construction geometry
- [ ] Do not copy internal geometry (ellipse, bspline etc)
- [ ] How to copy constraints on internal geometry?
- [ ] Copying of arc of ellipse/parabola/hyperbola

## Additional features
- [ ] Coincident constraint on copied point lying on the mirror line.
- [ ] Copy constraints between copied geometry and mirror geometry (PointOnObject, Tanget etc). Slightly risky if mirror line not fully constrained perhaps? Might also need special handling with axes/origin?
- [ ] Specifically for sketch points, it does not make sense to copy if they are on the mirror geometry, that results in two points on top of each other.
